### ISSUE TITLE
Bounty Board + Bounty Card

### ISSUE THREAD

**Issue by HeyMaximus** [Bebop-Bounty/bebop-bounty#5]
https://github.com/Bebop-Bounty/bebop-bounty/blob/77e95a3dd7304a11bd01065980c962eee03cb003/client/src/components/BountyPage/BountyBoard.jsx#L9

The Bounty Card is currently pass the full Context. 
Don't we want to parse Context and call .map() on an array of bounties to pass bounty data to Bounty Card one-at-a-time?

Asking because I need to import the Bounty Card component to use.

**Comment by swinnik** [comment]
yes, i will be updating this once we have a context. i didn't want to map over an empty array in the meantime... thanks for asking!
